name: Docker CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - src/**
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5  # Actualiza a v5 para usar Node.js 20
          
      - name: Login to DockerHub
        uses: docker/login-action@v4  # Actualiza a v4 para usar Node.js 20
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }} plaracil/examen:latest

# https://github.com/docker/build-push-action
# https://github.com/docker/login-action




# https://github.com/docker/login-action
# https://github.com/docker/build-push-action
# https://github.com/appleboy/ssh-action